create or replace force editionable view rmais_issuer_info_v (
    cnpj,
    receiver,
    total_po,
    po_header_id,
    po_num,
    po_type,
    tomador,
    tomador_cnpj,
    prc_bu_id,
    vendor_name,
    vendor_id,
    vendor_site_id,
    vendor_site_code,
    fornecedor_cnpj,
    currency_code,
    info_doc,
    info_term,
    po_seq,
    info_po,
    info_item,
    info_ship,
    po_line_id,
    line_type_id,
    line_num,
    item_id,
    category_id,
    item_description,
    uom_code,
    uom_desc,
    unit_price,
    quantity_line,
    prc_bu_id_lin,
    req_bu_id_lin,
    taxable_flag_lin,
    order_type_lookup_code,
    purchase_basis,
    matching_basis,
    line_location_id,
    destination_type_code,
    trx_business_category,
    prc_bu_id_loc,
    req_bu_id_loc,
    product_type,
    assessable_value,
    quantity_ship,
    quantity_received,
    quantity_accepted,
    quantity_rejected,
    quantity_billed,
    quantity_cancelled,
    ship_to_location_id,
    need_by_date,
    promised_date,
    last_accept_date,
    price_override,
    taxable_flag,
    receipt_required_flag,
    ship_to_organization_id,
    shipment_num,
    shipment_type,
    funds_status,
    destination_type_dist,
    prc_bu_id_dist,
    req_bu_id_dist,
    encumbered_flag,
    unencumbered_quantity,
    amount_billed,
    amount_cancelled,
    quantity_financed,
    amount_financed,
    quantity_recouped,
    amount_recouped,
    retainage_withheld_amount,
    retainage_released_amount,
    tax_attribute_update_code,
    po_distribution_id,
    budget_date,
    close_budget_date,
    dist_intended_use,
    set_of_books_id,
    code_combination_id,
    quantity_ordered,
    quantity_delivered,
    consignment_quantity,
    req_distribution_id,
    deliver_to_location_id,
    deliver_to_person_id,
    rate_date,
    rate,
    accrued_flag,
    encumbered_amount,
    unencumbered_amount,
    destination_organization_id,
    pjc_task_id,
    task_number,
    task_id,
    location_id,
    country,
    postal_code,
    local_description,
    effective_start_date,
    effective_end_date,
    business_group_id,
    active_status,
    ship_to_site_flag,
    receiving_site_flag,
    bill_to_site_flag,
    office_site_flag,
    inventory_organization_id,
    action_occurrence_id,
    location_code,
    location_name,
    style,
    address_line_1,
    address_line_2,
    address_line_3,
    address_line_4,
    region_1,
    region_2,
    town_or_city,
    line_seq,
    inventory_item_id,
    primary_uom_code,
    item_type,
    inventory_item_flag,
    tax_code,
    enabled_flag,
    item_number,
    description,
    long_description,
    ncm,
    catalog_code_ncm,
    destination_type,
    seq
) as
    select
        cnpj,
        receiver,
        total_po,
        po_header_id,
        po_num,
        po_type,
        tomador,
        tomador_cnpj,
        prc_bu_id,
        vendor_name,
        vendor_id,
        vendor_site_id,
        vendor_site_code,
        fornecedor_cnpj,
        currency_code,
        info_doc,
        info_term,
        po_seq,
        info_po,
        info_item,
        info_ship,
        po_line_id,
        line_type_id,
        line_num,
        item_id,
        category_id,
        item_description,
        uom_code,
        uom_desc,
        unit_price,
        quantity_line,
        prc_bu_id_lin,
        req_bu_id_lin,
        taxable_flag_lin,
        order_type_lookup_code,
        purchase_basis,
        matching_basis,
        line_location_id,
        destination_type_code,
        trx_business_category,
        prc_bu_id_loc,
        req_bu_id_loc,
        product_type,
        assessable_value,
        quantity_ship,
        quantity_received,
        quantity_accepted,
        quantity_rejected,
        quantity_billed,
        quantity_cancelled,
        ship_to_location_id,
        need_by_date,
        promised_date,
        last_accept_date,
        price_override,
        taxable_flag,
        receipt_required_flag,
        ship_to_organization_id,
        shipment_num,
        shipment_type,
        funds_status,
        destination_type_dist,
        prc_bu_id_dist,
        req_bu_id_dist,
        encumbered_flag,
        unencumbered_quantity,
        amount_billed,
        amount_cancelled,
        quantity_financed,
        amount_financed,
        quantity_recouped,
        amount_recouped,
        retainage_withheld_amount,
        retainage_released_amount,
        tax_attribute_update_code,
        po_distribution_id,
        budget_date,
        close_budget_date,
        dist_intended_use,
        set_of_books_id,
        code_combination_id,
        quantity_ordered,
        quantity_delivered,
        consignment_quantity,
        req_distribution_id,
        deliver_to_location_id,
        deliver_to_person_id,
        rate_date,
        rate,
        accrued_flag,
        encumbered_amount,
        unencumbered_amount,
        destination_organization_id,
        pjc_task_id,
        task_number,
        task_id,
        location_id,
        country,
        postal_code,
        local_description,
        effective_start_date,
        effective_end_date,
        business_group_id,
        active_status,
        ship_to_site_flag,
        receiving_site_flag,
        bill_to_site_flag,
        office_site_flag,
        inventory_organization_id,
        action_occurrence_id,
        location_code,
        location_name,
        style,
        address_line_1,
        address_line_2,
        address_line_3,
        address_line_4,
        region_1,
        region_2,
        town_or_city,
        line_seq,
        inventory_item_id,
        primary_uom_code,
        item_type,
        inventory_item_flag,
        tax_code,
        enabled_flag,
        item_number,
        description,
        long_description,
        ncm,
        catalog_code_ncm,
        destination_type,
        seq
    from
        (
            select
                p.cnpj,
                p.receiver,
                sum(nvl(d.price_override * quantity_ship, d.unit_price * d.quantity_line))
                over(partition by po_header_id)                   total_po,
                d.*,
                nvl(destination_type_code, destination_type_dist) destination_type,
                row_number()
                over(partition by d.po_header_id, d.po_line_id
                     order by
                         d.po_line_id, d.shipment_num
                )                                                 seq
            from
                rmais_issuer_info p,
                json_table ( p.docs, '$'
                        columns (
                            nested path '$.HEADER[*]'
                                columns (
                                    po_header_id number path '$.PO_HEADER_ID',
                                    po_num varchar2 ( 500 ) path '$.PO_NUM',
                                    po_type varchar2 ( 500 ) path '$.PO_TYPE',
                                    tomador varchar2 ( 300 ) path '$.TOMADOR',
                                    tomador_cnpj varchar2 ( 200 ) path '$.TOMADOR_CNPJ',
                                    prc_bu_id number path '$.PRC_BU_ID',
                                    vendor_name varchar2 ( 300 ) path '$.VENDOR_NAME',
                                    vendor_id number path '$.VENDOR_ID',
                                    vendor_site_id number path '$.VENDOR_SITE_ID',
                                    vendor_site_code varchar2 ( 100 ) path '$.VENDOR_SITE_CODE',
                                    fornecedor_cnpj varchar2 ( 200 ) path '$.FORNECEDOR_CNPJ',
                                    currency_code varchar2 ( 100 ) path '$.CURRENCY_CODE',
                                    info_doc clob format json with wrapper path '$',
                                    info_term clob format json with wrapper path '$.TERM',
                                    po_seq for ordinality,
                                    nested path '$.LINES[*]'
                                        columns (
                                            info_po clob format json with wrapper path '$',
                                            info_item clob format json with wrapper path '$.ITEM',
                                            info_ship clob format json with wrapper path '$.LINE_LOCATIONS',
                                            po_line_id number path '$.PO_LINE_ID',
                                            line_type_id number path '$.LINE_TYPE_ID',
                                            line_num number path '$.LINE_NUM',
                                            item_id number path '$.ITEM_ID',
                                            category_id number path '$.CATEGORY_ID',
                                            item_description varchar2 ( 300 ) path '$.ITEM_DESCRIPTION',
                                            uom_code varchar2 ( 100 ) path '$.UOM_CODE',
                                            uom_desc varchar2 ( 100 ) path '$.UOM_CODE',
                                            unit_price number path '$.UNIT_PRICE',
                                            quantity_line number path '$.QUANTITY',
                                            prc_bu_id_lin number path '$.PRC_BU_ID',
                                            req_bu_id_lin number path '$.REQ_BU_ID',
                                            taxable_flag_lin varchar2 ( 100 ) path '$.TAXABLE_FLAG',
                                            order_type_lookup_code varchar2 ( 100 ) path '$.ORDER_TYPE_LOOKUP_CODE',
                                            purchase_basis varchar2 ( 100 ) path '$.PURCHASE_BASIS',
                                            matching_basis varchar2 ( 100 ) path '$.MATCHING_BASIS',
                                            line_seq for ordinality,
                                            nested path '$.ITEM[*]'
                                                columns (
     --info_item CLOB FORMAT JSON  PATH '$[*]',
                                                    inventory_item_id number path '$.INVENTORY_ITEM_ID',
                                                    primary_uom_code varchar2 ( 100 ) path '$.PRIMARY_UOM_CODE',
                                                    item_type varchar2 ( 900 ) path '$.ITEM_TYPE',
                                                    inventory_item_flag varchar2 ( 100 ) path '$.INVENTORY_ITEM_FLAG',
                                                    tax_code varchar2 ( 500 ) path '$.TAX_CODE',
                                                    enabled_flag varchar2 ( 100 ) path '$.ENABLED_FLAG',
                                                    item_number varchar2 ( 300 ) path '$.ITEM_NUMBER',
                                                    description varchar2 ( 300 ) path '$.DESCRIPTION',
                                                    long_description varchar2 ( 900 ) path '$.LONG_DESCRIPTION',
                                                    ncm varchar2 ( 100 ) path '$.NCM',
                                                    catalog_code_ncm varchar2 ( 100 ) path '$.CATALOG_CODE'
                                                ),
                                            line_location_id number path '$.LINE_LOCATIONS.LINE_LOCATION_ID',
                                            destination_type_code varchar2 ( 900 ) path '$.LINE_LOCATIONS.DESTINATION_TYPE_CODE',
                                            trx_business_category varchar2 ( 900 ) path '$.LINE_LOCATIONS.TRX_BUSINESS_CATEGORY',
                                            prc_bu_id_loc number path '$.LINE_LOCATIONS.PRC_BU_ID',
                                            req_bu_id_loc number path '$.LINE_LOCATIONS.REQ_BU_ID',
                                            product_type varchar2 ( 100 ) path '$.LINE_LOCATIONS.PRODUCT_TYPE',
                                            assessable_value number path '$.LINE_LOCATIONS.ASSESSABLE_VALUE',
                                            quantity_ship number path '$.LINE_LOCATIONS.QUANTITY',
                                            quantity_received number path '$.LINE_LOCATIONS.QUANTITY_RECEIVED',
                                            quantity_accepted number path '$.LINE_LOCATIONS.QUANTITY_ACCEPTED',
                                            quantity_rejected number path '$.LINE_LOCATIONS.QUANTITY_REJECTED',
                                            quantity_billed number path '$.LINE_LOCATIONS.QUANTITY_BILLED',
                                            quantity_cancelled number path '$.LINE_LOCATIONS.QUANTITY_CANCELLED',
                                            ship_to_location_id number path '$.LINE_LOCATIONS.SHIP_TO_LOCATION_ID',
                                            need_by_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.NEED_BY_DATE',
                                            promised_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.PROMISED_DATE',
                                            last_accept_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.LAST_ACCEPT_DATE',
                                            price_override number path '$.LINE_LOCATIONS.PRICE_OVERRIDE',
                                            taxable_flag varchar2 ( 10 ) path '$.LINE_LOCATIONS.TAXABLE_FLAG',
                                            receipt_required_flag varchar2 ( 10 ) path '$.LINE_LOCATIONS.RECEIPT_REQUIRED_FLAG',
                                            ship_to_organization_id number path '$.LINE_LOCATIONS.SHIP_TO_ORGANIZATION_ID',
                                            shipment_num varchar2 ( 10 ) path '$.LINE_LOCATIONS.SHIPMENT_NUM',
                                            shipment_type varchar2 ( 500 ) path '$.LINE_LOCATIONS.SHIPMENT_TYPE',
                                            funds_status varchar2 ( 500 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.FUNDS_STATUS',
                                            destination_type_dist varchar2 ( 500 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.DESTINATION_TYPE_CODE'
                                            ,
                                            prc_bu_id_dist number path '$.LINE_LOCATIONS.DISTRIBUTIONS.PRC_BU_ID',
                                            req_bu_id_dist number path '$.LINE_LOCATIONS.DISTRIBUTIONS.REQ_BU_ID',
                                            encumbered_flag varchar2 ( 10 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.ENCUMBERED_FLAG',
                                            unencumbered_quantity number path '$.LINE_LOCATIONS.DISTRIBUTIONS.UNENCUMBERED_QUANTITY',
                                            amount_billed number path '$.LINE_LOCATIONS.DISTRIBUTIONS.AMOUNT_BILLED',
                                            amount_cancelled number path '$.LINE_LOCATIONS.DISTRIBUTIONS.AMOUNT_CANCELLED',
                                            quantity_financed number path '$.LINE_LOCATIONS.DISTRIBUTIONS.QUANTITY_FINANCED',
                                            amount_financed number path '$.LINE_LOCATIONS.DISTRIBUTIONS.AMOUNT_FINANCED',
                                            quantity_recouped number path '$.LINE_LOCATIONS.DISTRIBUTIONS.QUANTITY_RECOUPED',
                                            amount_recouped number path '$.LINE_LOCATIONS.DISTRIBUTIONS.AMOUNT_RECOUPED',
                                            retainage_withheld_amount number path '$.LINE_LOCATIONS.DISTRIBUTIONS.RETAINAGE_WITHHELD_AMOUNT'
                                            ,
                                            retainage_released_amount number path '$.LINE_LOCATIONS.DISTRIBUTIONS.RETAINAGE_RELEASED_AMOUNT'
                                            ,
                                            tax_attribute_update_code varchar2 ( 100 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.TAX_ATTRIBUTE_UPDATE_CODE'
                                            ,
                                            po_distribution_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.PO_DISTRIBUTION_ID',
                                            budget_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.BUDGET_DATE',
                                            close_budget_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.CLOSE_BUDGET_DATE'
                                            ,
                                            dist_intended_use varchar2 ( 500 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.DIST_INTENDED_USE'
                                            ,
                                            set_of_books_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.SET_OF_BOOKS_ID',
                                            code_combination_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.CODE_COMBINATION_ID',
                                            quantity_ordered number path '$.LINE_LOCATIONS.DISTRIBUTIONS.QUANTITY_ORDERED',
                                            quantity_delivered number path '$.LINE_LOCATIONS.DISTRIBUTIONS.QUANTITY_DELIVERED',
                                            consignment_quantity number path '$.LINE_LOCATIONS.DISTRIBUTIONS.CONSIGNMENT_QUANTITY',
                                            req_distribution_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.REQ_DISTRIBUTION_ID',
                                            deliver_to_location_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.DELIVER_TO_LOCATION_ID'
                                            ,
                                            deliver_to_person_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.DELIVER_TO_PERSON_ID',
                                            rate_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.RATE_DATE',
                                            rate number path '$.LINE_LOCATIONS.DISTRIBUTIONS.RATE',
                                            accrued_flag varchar2 ( 50 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.ACCRUED_FLAG',
                                            encumbered_amount number path '$.LINE_LOCATIONS.DISTRIBUTIONS.ENCUMBERED_AMOUNT',
                                            unencumbered_amount number path '$.LINE_LOCATIONS.DISTRIBUTIONS.UNENCUMBERED_AMOUNT',
                                            destination_organization_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.DESTINATION_ORGANIZATION_ID'
                                            ,
                                            pjc_task_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.PJC_TASK_ID',
                                            task_number varchar2 ( 200 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.TASKS.TASK_NUMBER',
                                            task_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.TASKS.TASK_ID',
                                            location_id number path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.LOCATION_ID',
                                            country varchar2 ( 500 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.COUNTRY',
                                            postal_code varchar2 ( 50 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.POSTAL_CODE',
                                            local_description varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.DESCRIPTION',
                                            effective_start_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.EFFECTIVE_START_DATE'
                                            ,
                                            effective_end_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.EFFECTIVE_END_DATE'
                                            ,
                                            business_group_id number path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.BUSINESS_GROUP_ID',
                                            active_status varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.ACTIVE_STATUS',
                                            ship_to_site_flag varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.SHIP_TO_SITE_FLAG'
                                            ,
                                            receiving_site_flag varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.RECEIVING_SITE_FLAG'
                                            ,
                                            bill_to_site_flag varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.BILL_TO_SITE_FLAG'
                                            ,
                                            office_site_flag varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.OFFICE_SITE_FLAG'
                                            ,
                                            inventory_organization_id number path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.INVENTORY_ORGANIZATION_ID'
                                            ,
                                            action_occurrence_id number path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.ACTION_OCCURRENCE_ID'
                                            ,
                                            location_code varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.LOCATION_CODE',
                                            location_name varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.LOCATION_NAME',
                                            style varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.STYLE',
                                            address_line_1 varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.ADDRESS_LINE_1',
                                            address_line_2 varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.ADDRESS_LINE_2',
                                            address_line_3 varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.ADDRESS_LINE_3',
                                            address_line_4 varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.ADDRESS_LINE_4',
                                            region_1 varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.REGION_1',
                                            region_2 varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.REGION_2',
                                            town_or_city varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.TOWN_OR_CITY'
                                        )
                                )
                        )
                    )
                d
        )
    where
        seq = 1;


-- sqlcl_snapshot {"hash":"23af62f5d78e7fc4aa79bd1d9fe851f1ebfa92b3","type":"VIEW","name":"RMAIS_ISSUER_INFO_V","schemaName":"RMAIS","sxml":""}