create or replace force editionable view rmais_efd_headers_v (
    efd_header_id,
    org_id,
    organization_id,
    location_id,
    layout_version,
    operation_type,
    document_type,
    ri_document_type_id,
    source_document_type,
    access_key_number,
    usage_authorization,
    event_code,
    event_type,
    event_date,
    document_number,
    series,
    model,
    issue_date,
    liable_freight_payment,
    dar_number,
    dar_total_amount,
    dar_payment_date,
    carrier_document_type,
    carrier_address_state,
    carrier_state_inscription,
    carrier_vehicle_plate_number,
    payment_term_id,
    payment_base_date,
    first_due_date,
    total_amount,
    issuing_purpose,
    issuing_type,
    freight_modal,
    gross_weight,
    freight_unit_of_measure,
    document_status_cod,
    document_status,
    additional_information,
    reject_reason,
    reject_justification,
    issuer_taxpayer_id,
    issuer_name,
    issuer_document_number,
    issuer_address,
    issuer_address_number,
    issuer_address_state,
    issuer_address_complement,
    issuer_address_zip_code,
    issuer_address_city_id,
    issuer_address_city_code,
    issuer_address_city_name,
    receiver_taxpayer_id,
    receiver_name,
    receiver_document_number,
    receiver_address,
    receiver_address_number,
    receiver_address_city_id,
    receiver_address_city_code,
    receiver_address_city_name,
    receiver_address_state,
    receiver_address_complement,
    receiver_address_zip_code,
    ship_from_document_number,
    ship_from_address_state,
    ship_from_address_city_code,
    ship_from_address_city_name,
    ship_from_address,
    ship_from_address_number,
    ship_from_address_zip_code,
    ship_from_address_complement,
    ship_to_document_number,
    ship_to_address,
    ship_to_address_number,
    ship_to_address_city_code,
    ship_to_address_city_name,
    ship_to_address_state,
    ship_to_address_zip_code,
    ship_to_address_complement,
    freight_amount,
    insurance_amount,
    other_expenses_amount,
    discount_amount,
    tributary_regimen,
    icms_calculation_basis,
    icms_amount,
    icms_st_calculation_basis,
    icms_st_amount,
    ipi_amount,
    pis_amount,
    cofins_amount,
    pis_withhold_amount,
    cofins_withhold_amount,
    ri_importing_indicator,
    file_name,
    email,
    process_date,
    source_type,
    creation_date,
    created_by,
    last_update_date,
    last_updated_by,
    last_update_login,
    program_id,
    program_login_id,
    program_application_id,
    request_id,
    attribute_category,
    attribute1,
    attribute2,
    attribute3,
    attribute4,
    attribute5,
    attribute6,
    attribute7,
    attribute8,
    attribute9,
    attribute10,
    attribute11,
    attribute12,
    attribute13,
    attribute14,
    attribute15,
    carrier_document_number,
    payment_indicator,
    freight_utilization_id,
    icms_fcp_amount,
    icms_sharing_dest_amount,
    icms_sharing_source_amount,
    operation_nature,
    service_taker_type,
    source,
    simple_national_indicator,
    freight_ibge_source,
    freight_city_source_code,
    freight_city_source_id,
    freight_ibge_destination,
    freight_city_dest_code,
    freight_city_dest_id,
    inss_income_code,
    inss_base,
    inss_tax,
    inss_amount,
    sest_senat_income_code,
    sest_amount,
    senat_amount,
    sest_tax,
    senat_tax,
    sest_base_amount,
    senat_base_amount,
    awt_group_id,
    operation,
    sest_senat_base,
    total_fcp_amount,
    total_fcp_st_amount,
    document_shipper_status,
    freight_flag,
    net_amount,
    source_state_code,
    source_ibge_code,
    destination_state_code,
    destination_ibge_code,
    sender_name,
    sender_document_number,
    sender_address_state,
    sender_address_city_code,
    sender_address_city_name,
    sender_address,
    sender_address_number,
    sender_address_complement,
    sender_address_zip_code,
    inss_billed_amount,
    referenced_chcte,
    observation,
    freight_mode,
    ir_amount,
    ir_base,
    ir_categ,
    ir_tax,
    ir_vendor,
    iss_amount,
    iss_tax,
    iss_base,
    iss_city_code,
    iss_city_id,
    checked_flag,
    checked_date,
    checked_by,
    submited_by,
    inss_init_base,
    boleto_associado,
    source_document_type_line_max,
    item_code_efd_max,
    flag_valid_boleto,
    icone,
    document_status_dash,
    poc
) as
    with tp_lines as (
        select
            b.efd_header_id,
            max(b.source_document_type) source_document_type_line_max,
            max(b.item_code_efd)        item_code_efd_max
        from
            rmais_efd_lines b
        group by
            b.efd_header_id
    )
    select
        h.efd_header_id,
        h.org_id,
        h.organization_id,
        h.location_id,
        h.layout_version,
        h.operation_type,
        h.document_type,
        h.ri_document_type_id,
        h.source_document_type,
        h.access_key_number,
        h.usage_authorization,
        h.event_code,
        h.event_type,
        h.event_date,
        h.document_number                                    document_number,
        h.series,
        decode(h.model, '55', 'NFe', '00', 'NFse',
               'NF', 'NF', '57', 'Cte', '67',
               'CTEos', '06', 'Energia', '21', 'Comunicação',
               '22', 'Telecomunicação', '28', 'Gás', '29',
               'Água', '97', 'Fatura de Aluguel', 'BO', 'Boleto',
               'Modelo Não suportado')                       as model,
        trunc(h.issue_date)                                  issue_date,
        h.liable_freight_payment,
        h.dar_number,
        h.dar_total_amount,
        h.dar_payment_date,
        h.carrier_document_type,
        h.carrier_address_state,
        h.carrier_state_inscription,
        h.carrier_vehicle_plate_number,
        h.payment_term_id,
        h.payment_base_date,
        h.first_due_date,
        to_char(h.total_amount, 'FML999G999G999G999G990D00') total_amount,
        h.issuing_purpose,
        h.issuing_type,
        h.freight_modal,
        h.gross_weight,
        h.freight_unit_of_measure
        --Comentado por Robson em 12/01/2023 ,decode(h.document_status,'N','A Receber','V','Válido','I','Inválido','E','Erro','T','Enviado ERP','C','Cancelada','M','Manual','X','Cancelada Após Integração','R','Rejeitado','RW','Rejeitado','W','Cancelada ERP','Status Desconhecido')  document_status
        ,
        h.document_status                                    document_status_cod,
        nvl(b.desc_status_docs, 'Status Desconhecido')       document_status
--        'colorizedCell ' || CASE WHEN (VALUE = 0 'redCell' ) THEN WHEN (VALUE > 100) THEN 'yellowCell' WHEN (VALUE = 50) THEN 'greenCell' ELSE 'whiteCell' END AS VALUE_DIV_CLASS
        --, document_status
        ,
        h.additional_information,
        h.reject_reason,
        h.reject_justification,
        h.issuer_taxpayer_id,
        initcap(h.issuer_name)                               issuer_name,
        h.issuer_document_number,
        h.issuer_address,
        h.issuer_address_number,
        h.issuer_address_state,
        h.issuer_address_complement,
        h.issuer_address_zip_code,
        h.issuer_address_city_id,
        h.issuer_address_city_code,
        h.issuer_address_city_name,
        h.receiver_taxpayer_id,
        initcap(org.nome)                                    receiver_name,
        org.cnpj                                             receiver_document_number 
        --h.receiver_document_number
        ,
        h.receiver_address,
        h.receiver_address_number,
        h.receiver_address_city_id,
        h.receiver_address_city_code,
        h.receiver_address_city_name,
        h.receiver_address_state,
        h.receiver_address_complement,
        h.receiver_address_zip_code,
        h.ship_from_document_number,
        h.ship_from_address_state,
        h.ship_from_address_city_code,
        h.ship_from_address_city_name,
        h.ship_from_address,
        h.ship_from_address_number,
        h.ship_from_address_zip_code,
        h.ship_from_address_complement,
        h.ship_to_document_number,
        h.ship_to_address,
        h.ship_to_address_number,
        h.ship_to_address_city_code,
        h.ship_to_address_city_name,
        h.ship_to_address_state,
        h.ship_to_address_zip_code,
        h.ship_to_address_complement,
        h.freight_amount,
        h.insurance_amount,
        h.other_expenses_amount,
        h.discount_amount,
        h.tributary_regimen,
        h.icms_calculation_basis,
        h.icms_amount,
        h.icms_st_calculation_basis,
        h.icms_st_amount,
        h.ipi_amount,
        h.pis_amount,
        h.cofins_amount,
        h.pis_withhold_amount,
        h.cofins_withhold_amount,
        h.ri_importing_indicator,
        h.file_name,
        h.email,
        h.process_date,
        h.source_type,
        trunc(h.creation_date)                               creation_date,
        h.created_by,
        h.last_update_date,
        h.last_updated_by,
        h.last_update_login,
        h.program_id,
        h.program_login_id,
        h.program_application_id,
        h.request_id,
        h.attribute_category,
        h.attribute1,
        h.attribute2,
        h.attribute3,
        h.attribute4,
        h.attribute5,
        h.attribute6,
        h.attribute7,
        h.attribute8,
        h.attribute9,
        h.attribute10,
        h.attribute11,
        h.attribute12,
        h.attribute13,
        h.attribute14,
        h.attribute15,
        h.carrier_document_number,
        h.payment_indicator,
        h.freight_utilization_id,
        h.icms_fcp_amount,
        h.icms_sharing_dest_amount,
        h.icms_sharing_source_amount,
        h.operation_nature,
        h.service_taker_type,
        h.source,
        h.simple_national_indicator,
        h.freight_ibge_source,
        h.freight_city_source_code,
        h.freight_city_source_id,
        h.freight_ibge_destination,
        h.freight_city_dest_code,
        h.freight_city_dest_id,
        h.inss_income_code,
        h.inss_base,
        h.inss_tax,
        h.inss_amount,
        h.sest_senat_income_code,
        h.sest_amount,
        h.senat_amount,
        h.sest_tax,
        h.senat_tax,
        h.sest_base_amount,
        h.senat_base_amount,
        h.awt_group_id,
        h.operation,
        h.sest_senat_base,
        h.total_fcp_amount,
        h.total_fcp_st_amount,
        h.document_shipper_status,
        h.freight_flag,
        h.net_amount,
        h.source_state_code,
        h.source_ibge_code,
        h.destination_state_code,
        h.destination_ibge_code,
        h.sender_name,
        h.sender_document_number,
        h.sender_address_state,
        h.sender_address_city_code,
        h.sender_address_city_name,
        h.sender_address,
        h.sender_address_number,
        h.sender_address_complement,
        h.sender_address_zip_code,
        h.inss_billed_amount,
        h.referenced_chcte,
        h.observation,
        h.freight_mode,
        h.ir_amount,
        h.ir_base,
        h.ir_categ,
        h.ir_tax,
        h.ir_vendor,
        h.iss_amount,
        h.iss_tax,
        h.iss_base,
        h.iss_city_code,
        h.iss_city_id,
        h.checked_flag,
        h.checked_date,
        h.checked_by,
        h.submited_by,
        h.inss_init_base,
        case
            when upper(nvl(h.flag_valid_boleto, 'N')) = 'Y' then
                'Sim'
            else
                'Não'
        end                                                  boleto_associado,
        c.source_document_type_line_max,
        c.item_code_efd_max,
        nvl(flag_valid_boleto, 'N')                          flag_valid_boleto,
        decode(
            nvl(flag_valid_boleto, 'N'),
            'Y',
            'fa fa-barcode',
            ''
        )                                                    icone,
        h.document_status                                    document_status_dash,
        h.poc
    from
        rmais_efd_headers   h,
        rmais_organizations org,
        rmais_status_docs   b,
        tp_lines            c
    where
        ( org.cnpj = h.receiver_document_number )--or 1=1)
        and h.document_status is not null
        and h.document_status not in ( 'FA', 'QA' ) -- Robson 23/03/2023
        and h.document_status = b.flag_status_docs (+)
        and h.efd_header_id = c.efd_header_id (+);


-- sqlcl_snapshot {"hash":"30405fcf0e860594311e443facf31a29b1b84b87","type":"VIEW","name":"RMAIS_EFD_HEADERS_V","schemaName":"RMAIS","sxml":""}