create or replace force editionable view rmais_get_po_line_vw (
    line_location_id,
    cnpj,
    receiver,
    total_po,
    po_header_id,
    po_num,
    po_type,
    tomador,
    tomador_cnpj,
    prc_bu_id,
    vendor_name,
    vendor_id,
    vendor_site_id,
    vendor_site_code,
    fornecedor_cnpj,
    currency_code,
    info_doc,
    info_term,
    po_seq,
    info_po,
    info_item,
    info_ship,
    po_line_id,
    line_type_id,
    line_num,
    item_id,
    category_id,
    item_description,
    uom_code,
    uom_desc,
    unit_price,
    quantity_line,
    prc_bu_id_lin,
    req_bu_id_lin,
    taxable_flag_lin,
    order_type_lookup_code,
    purchase_basis,
    matching_basis,
    destination_type_code,
    trx_business_category,
    prc_bu_id_loc,
    req_bu_id_loc,
    product_type,
    assessable_value,
    quantity_ship,
    quantity_received,
    quantity_accepted,
    quantity_rejected,
    quantity_billed,
    quantity_cancelled,
    ship_to_location_id,
    need_by_date,
    promised_date,
    last_accept_date,
    price_override,
    taxable_flag,
    receipt_required_flag,
    ship_to_organization_id,
    shipment_num,
    shipment_type,
    funds_status,
    destination_type_dist,
    prc_bu_id_dist,
    req_bu_id_dist,
    encumbered_flag,
    unencumbered_quantity,
    amount_billed,
    amount_cancelled,
    quantity_financed,
    amount_financed,
    quantity_recouped,
    amount_recouped,
    retainage_withheld_amount,
    retainage_released_amount,
    tax_attribute_update_code,
    po_distribution_id,
    budget_date,
    close_budget_date,
    dist_intended_use,
    set_of_books_id,
    code_combination_id,
    quantity_ordered,
    quantity_delivered,
    consignment_quantity,
    req_distribution_id,
    deliver_to_location_id,
    deliver_to_person_id,
    rate_date,
    rate,
    accrued_flag,
    encumbered_amount,
    unencumbered_amount,
    destination_organization_id,
    pjc_task_id,
    task_number,
    task_id,
    location_id,
    country,
    postal_code,
    local_description,
    effective_start_date,
    effective_end_date,
    business_group_id,
    active_status,
    ship_to_site_flag,
    receiving_site_flag,
    bill_to_site_flag,
    office_site_flag,
    inventory_organization_id,
    action_occurrence_id,
    location_code,
    location_name,
    style,
    address_line_1,
    address_line_2,
    address_line_3,
    address_line_4,
    region_1,
    region_2,
    town_or_city,
    line_seq,
    inventory_item_id,
    primary_uom_code,
    item_type,
    inventory_item_flag,
    tax_code,
    enabled_flag,
    item_number,
    description,
    long_description,
    ncm,
    catalog_code_ncm,
    destination_type,
    match_option,
    receipt_num,
    receipt_line_num,
    receipt_quantity_deliv
) as
    select distinct
        a.line_location_id,
        a.cnpj,
        a.receiver,
        a.total_po,
        a.po_header_id,
        a.po_num,
        a.po_type,
        a.tomador,
        a.tomador_cnpj,
        a.prc_bu_id,
        a.vendor_name,
        a.vendor_id,
        a.vendor_site_id,
        a.vendor_site_code,
        a.fornecedor_cnpj,
        a.currency_code,
        a.info_doc,
        a.info_term,
        a.po_seq,
        a.info_po,
        a.info_item,
        a.info_ship,
        a.po_line_id,
        a.line_type_id,
        a.line_num,
        a.item_id,
        a.category_id,
        a.item_description,
        nvl(a.primary_uom_code,
            max(a.primary_uom_code)
            over(partition by a.line_location_id))                uom_code,
        nvl(a.uom_code_po,
            max(a.uom_code_po)
            over(partition by a.line_location_id))                uom_desc,
                --nvl(UNIT_OF_MEASURE_PO,UOM_CODE2) UOM_DESC -- baseado no get_po_line
        a.unit_price,
        a.quantity_line,
        a.prc_bu_id_lin,
        a.req_bu_id_lin,
        a.taxable_flag_lin,
        a.order_type_lookup_code,
        a.purchase_basis,
        a.matching_basis,
        a.destination_type_code,
        a.trx_business_category,
        a.prc_bu_id_loc,
        a.req_bu_id_loc,
        a.product_type,
        a.assessable_value,
        a.quantity_ship,
        a.quantity_received,
        a.quantity_accepted,
        a.quantity_rejected,
        a.quantity_billed,
        a.quantity_cancelled,
        a.ship_to_location_id,
        to_char(a.need_by_date)                               need_by_date,
        to_char(a.promised_date)                              promised_date,
        a.last_accept_date,
        a.price_override,
        a.taxable_flag,
        a.receipt_required_flag,
        a.ship_to_organization_id,
        a.shipment_num,
        a.shipment_type,
        a.funds_status,
        a.destination_type_dist,
        a.prc_bu_id_dist,
        a.req_bu_id_dist,
        a.encumbered_flag,
        a.unencumbered_quantity,
        a.amount_billed,
        a.amount_cancelled,
        a.quantity_financed,
        a.amount_financed,
        a.quantity_recouped,
        a.amount_recouped,
        a.retainage_withheld_amount,
        a.retainage_released_amount,
        a.tax_attribute_update_code,
        a.po_distribution_id,
        a.budget_date,
        a.close_budget_date,
        a.dist_intended_use,
        a.set_of_books_id,
        a.code_combination_id,
        a.quantity_ordered,
        a.quantity_delivered,
        a.consignment_quantity,
        a.req_distribution_id,
        a.deliver_to_location_id,
        a.deliver_to_person_id,
        a.rate_date,
        a.rate,
        a.accrued_flag,
        a.encumbered_amount,
        a.unencumbered_amount,
        a.destination_organization_id,
        a.pjc_task_id,
        a.task_number,
        a.task_id,
        a.location_id,
        a.country,
        a.postal_code,
        a.local_description,
        a.effective_start_date,
        a.effective_end_date,
        a.business_group_id,
        a.active_status,
        a.ship_to_site_flag,
        a.receiving_site_flag,
        a.bill_to_site_flag,
        a.office_site_flag,
        a.inventory_organization_id,
        a.action_occurrence_id,
        a.location_code,
        a.location_name,
        a.style,
        a.address_line_1,
        a.address_line_2,
        a.address_line_3,
        a.address_line_4,
        a.region_1,
        a.region_2,
        a.town_or_city,
        a.line_seq,
        nvl(a.inventory_item_id,
            max(a.inventory_item_id)
            over(partition by a.line_location_id))                inventory_item_id,
        nvl(a.primary_uom_code,
            max(a.primary_uom_code)
            over(partition by a.line_location_id))                primary_uom_code,
        nvl(a.item_type,
            max(a.item_type)
            over(partition by a.line_location_id))                item_type,
        nvl(a.inventory_item_flag,
            max(a.inventory_item_flag)
            over(partition by a.line_location_id))                inventory_item_flag,
        a.tax_code,
        nvl(a.enabled_flag,
            max(a.enabled_flag)
            over(partition by a.line_location_id))                enabled_flag,
        nvl(a.item_number,
            max(a.item_number)
            over(partition by a.line_location_id))                item_number,
        nvl(a.description,
            max(a.description)
            over(partition by a.line_location_id))                description,
        nvl(a.long_description,
            max(a.long_description)
            over(partition by a.line_location_id))                long_description,
        a.ncm,
        a.catalog_code_ncm,
        nvl(a.destination_type_code, a.destination_type_dist) destination_type,
        a.match_option,
        nvl(a.receipt_num,
            max(a.receipt_num)
            over(partition by a.line_location_id))                receipt_num,
        nvl(a.receipt_line_num,
            max(a.receipt_line_num)
            over(partition by a.line_location_id))                receipt_line_num,
        nvl(a.receipt_quantity_deliv,
            max(a.receipt_quantity_deliv)
            over(partition by a.line_location_id))                receipt_quantity_deliv
    from
        (
            select
                p.transaction_id,
                d.fornecedor_cnpj               cnpj,
                d.tomador_cnpj                  receiver,
                sum(nvl(d.price_override * quantity_ship, d.unit_price * d.quantity_line))
                over(partition by po_header_id) total_po,
                            --SUM(NVL(nls_num_char(D.price_override) * nls_num_char(quantity_ship),nls_num_char(D.UNIT_PRICE) * nls_num_char(D.QUANTITY_LINE))) OVER (PARTITION BY PO_HEADER_ID) TOTAL_PO
                d.*
            from
                rmais_ws_info p,
                json_table ( replace(
                        replace(
                            replace(
                                replace(
                                    xxrmais_util_pkg.base64decode(p.clob_info),
                                    '"RECEIPT":{',
                                    '"RECEIPT":[{'
                                ),
                                '"DESTINATION_TYPE_CODE":"RECEIVING"}}',
                                '"DESTINATION_TYPE_CODE":"RECEIVING"}]}'
                            ),
                            '"LINE_LOCATIONS":{',
                            '"LINE_LOCATIONS":[{'
                        ),
                        '},"ITEM":',
                        '}],"ITEM":'
                    ), '$'
                        columns (
                            nested path '$.HEADER[*]'
                                columns (
                                    po_header_id number path '$.PO_HEADER_ID',
                                    po_num varchar2 ( 500 ) path '$.PO_NUM',
                                    po_type varchar2 ( 500 ) path '$.PO_TYPE',
                                    tomador varchar2 ( 300 ) path '$.TOMADOR',
                                    tomador_cnpj varchar2 ( 200 ) path '$.TOMADOR_CNPJ',
                                    prc_bu_id number path '$.PRC_BU_ID',
                                    vendor_name varchar2 ( 300 ) path '$.VENDOR_NAME',
                                    vendor_id number path '$.VENDOR_ID',
                                    vendor_site_id number path '$.VENDOR_SITE_ID',
                                    vendor_site_code varchar2 ( 100 ) path '$.VENDOR_SITE_CODE',
                                    fornecedor_cnpj varchar2 ( 200 ) path '$.FORNECEDOR_CNPJ',
                                    currency_code varchar2 ( 100 ) path '$.CURRENCY_CODE',
                                    info_doc varchar2 ( 4000 ) format json with wrapper path '$',
                                    info_term varchar2 ( 4000 ) format json with wrapper path '$.TERM',
                                    po_seq for ordinality,
                                    nested path '$.LINES[*]'
                                        columns (
                                            info_po varchar2 ( 4000 ) format json with wrapper path '$',
                                            info_item varchar2 ( 4000 ) format json with wrapper path '$.ITEM',
                                            info_ship varchar2 ( 4000 ) format json with wrapper path '$.LINE_LOCATIONS',
                                            po_line_id number path '$.PO_LINE_ID',
                                            line_type_id number path '$.LINE_TYPE_ID',
                                            line_num number path '$.LINE_NUM',
                                            item_id number path '$.ITEM_ID',
                                            category_id number path '$.CATEGORY_ID',
                                            item_description varchar2 ( 300 ) path '$.ITEM_DESCRIPTION',
                                            uom_code_po varchar2 ( 100 ) path '$.UOM_CODE',
                                            unit_price number path '$.UNIT_PRICE',
                                            quantity_line number path '$.QUANTITY',
                                            nested path '$.LINE_LOCATIONS[*].RECEIPT[*]'
                                                columns ( -- Adicionado 23/01/2023 Robson
                                                    receipt_num varchar2 ( 900 ) path '$.RECEIPT_NUM',
                                                    receipt_line_num varchar2 ( 900 ) path '$.LINE_NUM',
                                                    receipt_quantity_deliv varchar2 ( 900 ) path '$.QUANTITY_DELIVERED',
                                                    input_tax_classification_code varchar2 ( 900 ) path '$.TAX_CLASSIFICATION_CODE',
                                                --TAX_RATE VARCHAR2(900) path '$.PERCENTAGE_RATE'
                                                    tax_rate2 varchar2 ( 900 ) path '$.PERCENTAGE_RATE'
                                                ),
                                            prc_bu_id_lin number path '$.PRC_BU_ID',
                                            req_bu_id_lin number path '$.REQ_BU_ID',
                                            taxable_flag_lin varchar2 ( 100 ) path '$.TAXABLE_FLAG',
                                            order_type_lookup_code varchar2 ( 100 ) path '$.ORDER_TYPE_LOOKUP_CODE',
                                            purchase_basis varchar2 ( 100 ) path '$.PURCHASE_BASIS',
                                            matching_basis varchar2 ( 100 ) path '$.MATCHING_BASIS',
                                            line_seq for ordinality,
                                            nested path '$.ITEM'
                                                columns (
                                                --info_item CLOB FORMAT JSON path '$[*]',
                                                    inventory_item_id number path '$.INVENTORY_ITEM_ID',
                                                    primary_uom_code varchar2 ( 100 ) path '$.PRIMARY_UOM_CODE',
                                                    item_type varchar2 ( 900 ) path '$.ITEM_TYPE',
                                                    inventory_item_flag varchar2 ( 100 ) path '$.INVENTORY_ITEM_FLAG',
                                                    tax_code varchar2 ( 500 ) path '$.TAX_CODE',
                                                    enabled_flag varchar2 ( 100 ) path '$.ENABLED_FLAG',
                                                    item_number varchar2 ( 300 ) path '$.ITEM_NUMBER',
                                                    description varchar2 ( 300 ) path '$.DESCRIPTION',
                                                    long_description varchar2 ( 900 ) path '$.LONG_DESCRIPTION',
                                                    ncm varchar2 ( 100 ) path '$.NCM',
                                                    catalog_code_ncm varchar2 ( 100 ) path '$.CATALOG_CODE',
                                                    uom_code varchar ( 100 ) path '$.UNIT_OF_MEASURE'
                                                ),
                                            line_location_id number path '$.LINE_LOCATIONS.LINE_LOCATION_ID',
                                            match_option varchar ( 100 ) path '$.LINE_LOCATIONS.MATCH_OPTION', -- Adicionado 23/01/2023 Robson
                                            destination_type_code varchar2 ( 900 ) path '$.LINE_LOCATIONS.DESTINATION_TYPE_CODE',
                                            trx_business_category varchar2 ( 900 ) path '$.LINE_LOCATIONS.TRX_BUSINESS_CATEGORY',
                                            prc_bu_id_loc number path '$.LINE_LOCATIONS.PRC_BU_ID',
                                            req_bu_id_loc number path '$.LINE_LOCATIONS.REQ_BU_ID',
                                            product_type varchar2 ( 100 ) path '$.LINE_LOCATIONS.PRODUCT_TYPE',
                                            assessable_value number path '$.LINE_LOCATIONS.ASSESSABLE_VALUE',
                                            quantity_ship number path '$.LINE_LOCATIONS.QUANTITY',
                                            quantity_received number path '$.LINE_LOCATIONS.QUANTITY_RECEIVED',
                                            quantity_accepted number path '$.LINE_LOCATIONS.QUANTITY_ACCEPTED',
                                            quantity_rejected number path '$.LINE_LOCATIONS.QUANTITY_REJECTED',
                                            quantity_billed number path '$.LINE_LOCATIONS.QUANTITY_BILLED',
                                            quantity_cancelled number path '$.LINE_LOCATIONS.QUANTITY_CANCELLED',
                                            ship_to_location_id number path '$.LINE_LOCATIONS.SHIP_TO_LOCATION_ID',
                                            need_by_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.NEED_BY_DATE',
                                            promised_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.PROMISED_DATE',
                                            last_accept_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.LAST_ACCEPT_DATE',
                                            price_override number path '$.LINE_LOCATIONS.PRICE_OVERRIDE',
                                            taxable_flag varchar2 ( 10 ) path '$.LINE_LOCATIONS.TAXABLE_FLAG',
                                            receipt_required_flag varchar2 ( 10 ) path '$.LINE_LOCATIONS.RECEIPT_REQUIRED_FLAG',
                                            ship_to_organization_id number path '$.LINE_LOCATIONS.SHIP_TO_ORGANIZATION_ID',
                                            shipment_num varchar2 ( 10 ) path '$.LINE_LOCATIONS.SHIPMENT_NUM',
                                            shipment_type varchar2 ( 500 ) path '$.LINE_LOCATIONS.SHIPMENT_TYPE',
                                            funds_status varchar2 ( 500 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.FUNDS_STATUS',
                                            destination_type_dist varchar2 ( 500 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.DESTINATION_TYPE_CODE'
                                            ,
                                            prc_bu_id_dist number path '$.LINE_LOCATIONS.DISTRIBUTIONS.PRC_BU_ID',
                                            req_bu_id_dist number path '$.LINE_LOCATIONS.DISTRIBUTIONS.REQ_BU_ID',
                                            encumbered_flag varchar2 ( 10 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.ENCUMBERED_FLAG',
                                            unencumbered_quantity number path '$.LINE_LOCATIONS.DISTRIBUTIONS.UNENCUMBERED_QUANTITY',
                                            amount_billed number path '$.LINE_LOCATIONS.DISTRIBUTIONS.AMOUNT_BILLED',
                                            amount_cancelled number path '$.LINE_LOCATIONS.DISTRIBUTIONS.AMOUNT_CANCELLED',
                                            quantity_financed number path '$.LINE_LOCATIONS.DISTRIBUTIONS.QUANTITY_FINANCED',
                                            amount_financed number path '$.LINE_LOCATIONS.DISTRIBUTIONS.AMOUNT_FINANCED',
                                            quantity_recouped number path '$.LINE_LOCATIONS.DISTRIBUTIONS.QUANTITY_RECOUPED',
                                            amount_recouped number path '$.LINE_LOCATIONS.DISTRIBUTIONS.AMOUNT_RECOUPED',
                                            retainage_withheld_amount number path '$.LINE_LOCATIONS.DISTRIBUTIONS.RETAINAGE_WITHHELD_AMOUNT'
                                            ,
                                            retainage_released_amount number path '$.LINE_LOCATIONS.DISTRIBUTIONS.RETAINAGE_RELEASED_AMOUNT'
                                            ,
                                            tax_attribute_update_code varchar2 ( 100 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.TAX_ATTRIBUTE_UPDATE_CODE'
                                            ,
                                            po_distribution_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.PO_DISTRIBUTION_ID',
                                            budget_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.BUDGET_DATE',
                                            close_budget_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.CLOSE_BUDGET_DATE'
                                            ,
                                            dist_intended_use varchar2 ( 500 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.DIST_INTENDED_USE'
                                            ,
                                            set_of_books_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.SET_OF_BOOKS_ID',
                                            code_combination_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.CODE_COMBINATION_ID',
                                            quantity_ordered number path '$.LINE_LOCATIONS.DISTRIBUTIONS.QUANTITY_ORDERED',
                                            quantity_delivered number path '$.LINE_LOCATIONS.DISTRIBUTIONS.QUANTITY_DELIVERED',
                                            consignment_quantity number path '$.LINE_LOCATIONS.DISTRIBUTIONS.CONSIGNMENT_QUANTITY',
                                            req_distribution_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.REQ_DISTRIBUTION_ID',
                                            deliver_to_location_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.DELIVER_TO_LOCATION_ID'
                                            ,
                                            deliver_to_person_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.DELIVER_TO_PERSON_ID',
                                            rate_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.RATE_DATE',
                                            rate number path '$.LINE_LOCATIONS.DISTRIBUTIONS.RATE',
                                            accrued_flag varchar2 ( 50 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.ACCRUED_FLAG',
                                            encumbered_amount number path '$.LINE_LOCATIONS.DISTRIBUTIONS.ENCUMBERED_AMOUNT',
                                            unencumbered_amount number path '$.LINE_LOCATIONS.DISTRIBUTIONS.UNENCUMBERED_AMOUNT',
                                            destination_organization_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.DESTINATION_ORGANIZATION_ID'
                                            ,
                                            pjc_task_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.PJC_TASK_ID',
                                            task_number varchar2 ( 200 ) path '$.LINE_LOCATIONS.DISTRIBUTIONS.TASKS.TASK_NUMBER',
                                            task_id number path '$.LINE_LOCATIONS.DISTRIBUTIONS.TASKS.TASK_ID',
                                            location_id number path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.LOCATION_ID',
                                            country varchar2 ( 500 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.COUNTRY',
                                            postal_code varchar2 ( 50 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.POSTAL_CODE',
                                            local_description varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.DESCRIPTION',
                                            effective_start_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.EFFECTIVE_START_DATE'
                                            ,
                                            effective_end_date varchar2 ( 50 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.EFFECTIVE_END_DATE'
                                            ,
                                            business_group_id number path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.BUSINESS_GROUP_ID',
                                            active_status varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.ACTIVE_STATUS',
                                            ship_to_site_flag varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.SHIP_TO_SITE_FLAG'
                                            ,
                                            receiving_site_flag varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.RECEIVING_SITE_FLAG'
                                            ,
                                            bill_to_site_flag varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.BILL_TO_SITE_FLAG'
                                            ,
                                            office_site_flag varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.OFFICE_SITE_FLAG'
                                            ,
                                            inventory_organization_id number path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.INVENTORY_ORGANIZATION_ID'
                                            ,
                                            action_occurrence_id number path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.ACTION_OCCURRENCE_ID'
                                            ,
                                            location_code varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.LOCATION_CODE',
                                            location_name varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.LOCATION_NAME',
                                            style varchar2 ( 100 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.STYLE',
                                            address_line_1 varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.ADDRESS_LINE_1',
                                            address_line_2 varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.ADDRESS_LINE_2',
                                            address_line_3 varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.ADDRESS_LINE_3',
                                            address_line_4 varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.ADDRESS_LINE_4',
                                            region_1 varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.REGION_1',
                                            region_2 varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.REGION_2',
                                            town_or_city varchar2 ( 300 ) path '$.LINE_LOCATIONS.SHIP_TO_LOCATION.TOWN_OR_CITY'
                                        )
                                )
                        )
                    )
                d
            where
                p.transaction_id = 0
        ) a --105736 :G_TRANSACTION_ID) A
    where
        a.match_option is not null
    order by
        a.po_num,
        a.line_num;


-- sqlcl_snapshot {"hash":"cfd5a2ce815945f20eae8c2d63197de2e1719b0b","type":"VIEW","name":"RMAIS_GET_PO_LINE_VW","schemaName":"RMAIS","sxml":""}