create or replace force editionable view vw_rmais_efd_headers (
    efd_header_id,
    org_id,
    organization_id,
    location_id,
    layout_version,
    operation_type,
    document_type,
    ri_document_type_id,
    source_document_type,
    access_key_number,
    usage_authorization,
    event_code,
    event_type,
    event_date,
    document_number,
    series,
    model,
    cod_model,
    issue_date,
    liable_freight_payment,
    dar_number,
    dar_total_amount,
    dar_payment_date,
    carrier_document_type,
    carrier_address_state,
    carrier_state_inscription,
    carrier_vehicle_plate_number,
    payment_term_id,
    payment_base_date,
    first_due_date,
    total_amount,
    total_amount_val,
    issuing_purpose,
    issuing_type,
    freight_modal,
    gross_weight,
    freight_unit_of_measure,
    document_status,
    cod_status,
    additional_information,
    reject_reason,
    reject_justification,
    issuer_taxpayer_id,
    issuer_name,
    issuer_document_number,
    issuer_address,
    issuer_address_number,
    issuer_address_state,
    issuer_address_complement,
    issuer_address_zip_code,
    issuer_address_city_id,
    issuer_address_city_code,
    issuer_address_city_name,
    receiver_taxpayer_id,
    receiver_name,
    receiver_document_number,
    receiver_address,
    receiver_address_number,
    receiver_address_city_id,
    receiver_address_city_code,
    receiver_address_city_name,
    receiver_address_state,
    receiver_address_complement,
    receiver_address_zip_code,
    ship_from_document_number,
    ship_from_address_state,
    ship_from_address_city_code,
    ship_from_address_city_name,
    ship_from_address,
    ship_from_address_number,
    ship_from_address_zip_code,
    ship_from_address_complement,
    ship_to_document_number,
    ship_to_address,
    ship_to_address_number,
    ship_to_address_city_code,
    ship_to_address_city_name,
    ship_to_address_state,
    ship_to_address_zip_code,
    ship_to_address_complement,
    freight_amount,
    insurance_amount,
    other_expenses_amount,
    discount_amount,
    tributary_regimen,
    icms_calculation_basis,
    icms_amount,
    icms_st_calculation_basis,
    icms_st_amount,
    ipi_amount,
    pis_amount,
    cofins_amount,
    pis_withhold_amount,
    cofins_withhold_amount,
    ri_importing_indicator,
    file_name,
    email,
    process_date,
    source_type,
    creation_date,
    created_by,
    last_update_date,
    last_updated_by,
    last_update_login,
    program_id,
    program_login_id,
    program_application_id,
    request_id,
    attribute_category,
    attribute1,
    attribute2,
    attribute3,
    attribute4,
    attribute5,
    attribute6,
    attribute7,
    attribute8,
    attribute9,
    attribute10,
    attribute11,
    attribute12,
    attribute13,
    attribute14,
    attribute15,
    carrier_document_number,
    payment_indicator,
    freight_utilization_id,
    icms_fcp_amount,
    icms_sharing_dest_amount,
    icms_sharing_source_amount,
    operation_nature,
    service_taker_type,
    source,
    simple_national_indicator,
    freight_ibge_source,
    freight_city_source_code,
    freight_city_source_id,
    freight_ibge_destination,
    freight_city_dest_code,
    freight_city_dest_id,
    inss_income_code,
    inss_base,
    inss_tax,
    inss_amount,
    sest_senat_income_code,
    sest_amount,
    senat_amount,
    sest_tax,
    senat_tax,
    sest_base_amount,
    senat_base_amount,
    awt_group_id,
    operation,
    sest_senat_base,
    total_fcp_amount,
    total_fcp_st_amount,
    document_shipper_status,
    freight_flag,
    net_amount,
    source_state_code,
    source_ibge_code,
    destination_state_code,
    destination_ibge_code,
    sender_name,
    sender_document_number,
    sender_address_state,
    sender_address_city_code,
    sender_address_city_name,
    sender_address,
    sender_address_number,
    sender_address_complement,
    sender_address_zip_code,
    inss_billed_amount,
    referenced_chcte,
    observation,
    freight_mode,
    ir_amount,
    ir_base,
    ir_categ,
    ir_tax,
    ir_vendor,
    iss_amount,
    iss_tax,
    iss_base,
    iss_city_code,
    iss_city_id,
    checked_flag,
    checked_date,
    checked_by,
    submited_by,
    inss_init_base,
    cod_identificador,
    flag_valid_boleto,
    icone,
    apresentar_linhas,
    total_impostos,
    lst_pedidos,
    id_boleto,
    bu_code
) as
    with tp_org as (
        select
            id_org
        from
            tb_grupo_ac_dados_org
        where
            id_grupo_acesso_dados = v('F_ID_GRUPO_ACESSO_DADOS')-- or 1=1
    ), tp_fornec as (
        select
            issuer_document_number
        from
            tb_grupo_ac_dados_fornec
        where
            id_grupo_acesso_dados = v('F_ID_GRUPO_ACESSO_DADOS')-- or 1=1
    ), tp_lines as (
        select
            efd_header_id,
            listagg(distinct source_doc_number, ';') within group(
            order by
                source_doc_number
            ) lst_pedidos,
            max(
                case
                    when nvl(source_document_type, '.') = 'PO' then
                        source_document_type
                end
            ) source_document_type
        from
            rmais_efd_lines
        where
            source_doc_number is not null
        group by
            efd_header_id,
            source_doc_number
    )
    select
        h.efd_header_id,
        h.org_id,
        h.organization_id,
        h.location_id,
        h.layout_version,
        h.operation_type,
        h.document_type,
        h.ri_document_type_id,
        h.source_document_type,
        h.access_key_number,
        h.usage_authorization,
        h.event_code,
        h.event_type,
        h.event_date,
        h.document_number,
        h.series,
        nvl(
            nvl(m.isv_name, m.model_name),
            'Modelo Não suportado'
        )                                                     model,
        nvl(m.isv_model, m.model)                             cod_model,
        h.issue_date,
        h.liable_freight_payment,
        h.dar_number,
        h.dar_total_amount,
        h.dar_payment_date,
        h.carrier_document_type,
        h.carrier_address_state,
        h.carrier_state_inscription,
        h.carrier_vehicle_plate_number,
        h.payment_term_id,
        h.payment_base_date,
        h.first_due_date,
        to_char(h.total_amount, 'FML999G999G999G999G990D00')  total_amount,
        h.total_amount                                        total_amount_val,
        h.issuing_purpose,
        h.issuing_type,
        h.freight_modal,
        h.gross_weight,
        h.freight_unit_of_measure,
        nvl(c.desc_status_docs, 'Status Desconhecido')        document_status,
        c.flag_status_docs                                    cod_status,
        h.additional_information,
        h.reject_reason,
        h.reject_justification,
        h.issuer_taxpayer_id,
        initcap(h.issuer_name)                                issuer_name,
        h.issuer_document_number,
        h.issuer_address,
        h.issuer_address_number,
        h.issuer_address_state,
        h.issuer_address_complement,
        h.issuer_address_zip_code,
        h.issuer_address_city_id,
        h.issuer_address_city_code,
        case
            when h.model = '00' then
                h.issuer_address_city_name
            else
                null
        end                                                   as issuer_address_city_name,
        h.receiver_taxpayer_id,
        initcap(org.nome)                                     receiver_name,
        org.cnpj                                              receiver_document_number 
    --h.receiver_document_number
        ,
        h.receiver_address,
        h.receiver_address_number,
        h.receiver_address_city_id,
        h.receiver_address_city_code,
        h.receiver_address_city_name,
        h.receiver_address_state,
        h.receiver_address_complement,
        h.receiver_address_zip_code,
        h.ship_from_document_number,
        h.ship_from_address_state,
        h.ship_from_address_city_code,
        h.ship_from_address_city_name,
        h.ship_from_address,
        h.ship_from_address_number,
        h.ship_from_address_zip_code,
        h.ship_from_address_complement,
        h.ship_to_document_number,
        h.ship_to_address,
        h.ship_to_address_number,
        h.ship_to_address_city_code,
        h.ship_to_address_city_name,
        h.ship_to_address_state,
        h.ship_to_address_zip_code,
        h.ship_to_address_complement,
        h.freight_amount,
        h.insurance_amount,
        h.other_expenses_amount,
        h.discount_amount,
        h.tributary_regimen,
        h.icms_calculation_basis,
        h.icms_amount,
        h.icms_st_calculation_basis,
        h.icms_st_amount,
        h.ipi_amount,
        h.pis_amount,
        h.cofins_amount,
        h.pis_withhold_amount,
        h.cofins_withhold_amount,
        h.ri_importing_indicator,
        h.file_name,
        h.email,
        h.process_date,
        h.source_type,
        h.creation_date,
        h.created_by,
        h.last_update_date,
        h.last_updated_by,
        h.last_update_login,
        h.program_id,
        h.program_login_id,
        h.program_application_id,
        h.request_id,
        h.attribute_category,
        h.attribute1,
        h.attribute2,
        h.attribute3,
        h.attribute4,
        h.attribute5,
        h.attribute6,
        h.attribute7,
        h.attribute8,
        h.attribute9,
        h.attribute10,
        h.attribute11,
        h.attribute12,
        h.attribute13,
        h.attribute14,
        h.attribute15,
        h.carrier_document_number,
        h.payment_indicator,
        h.freight_utilization_id,
        h.icms_fcp_amount,
        h.icms_sharing_dest_amount,
        h.icms_sharing_source_amount,
        h.operation_nature,
        h.service_taker_type,
        h.source,
        h.simple_national_indicator,
        h.freight_ibge_source,
        h.freight_city_source_code,
        h.freight_city_source_id,
        h.freight_ibge_destination,
        h.freight_city_dest_code,
        h.freight_city_dest_id,
        h.inss_income_code,
        h.inss_base,
        h.inss_tax,
        h.inss_amount,
        h.sest_senat_income_code,
        h.sest_amount,
        h.senat_amount,
        h.sest_tax,
        h.senat_tax,
        h.sest_base_amount,
        h.senat_base_amount,
        h.awt_group_id,
        h.operation,
        h.sest_senat_base,
        h.total_fcp_amount,
        h.total_fcp_st_amount,
        h.document_shipper_status,
        h.freight_flag,
        h.net_amount,
        h.source_state_code,
        h.source_ibge_code,
        h.destination_state_code,
        h.destination_ibge_code,
        h.sender_name,
        h.sender_document_number,
        h.sender_address_state,
        h.sender_address_city_code,
        h.sender_address_city_name,
        h.sender_address,
        h.sender_address_number,
        h.sender_address_complement,
        h.sender_address_zip_code,
        h.inss_billed_amount,
        h.referenced_chcte,
        h.observation,
        h.freight_mode,
        h.ir_amount,
        h.ir_base,
        h.ir_categ,
        h.ir_tax,
        h.ir_vendor,
        h.iss_amount,
        h.iss_tax,
        h.iss_base,
        h.iss_city_code,
        h.iss_city_id,
        h.checked_flag,
        h.checked_date,
        h.checked_by,
        h.submited_by,
        h.inss_init_base
    --,rmt.cod1 cod_identificador
        ,
        rmais_process_pkg.get_cc_cod_cliente(h.efd_header_id) cod_identificador,
        nvl(flag_valid_boleto, 'N')                           flag_valid_boleto,
        decode(
            nvl(flag_valid_boleto, 'N'),
            'Y',
            'fa fa-barcode',
            ''
        )                                                     icone,
        case
            when document_type = 'NA'
                 or document_status = 'T' then
                'S'
            else
                'N'
        end                                                   apresentar_linhas,
        to_char(nvl(icms_amount, 0) + nvl(icms_st_amount, 0) + nvl(ipi_amount, 0) + nvl(pis_amount, 0) + nvl(cofins_amount, 0) + nvl(
        pis_withhold_amount, 0) + nvl(cofins_withhold_amount, 0) + nvl(icms_fcp_amount, 0) + nvl(icms_sharing_dest_amount, 0) + nvl(icms_sharing_source_amount
        , 0) + nvl(inss_amount, 0) + nvl(dar_total_amount, 0) + nvl(sest_amount, 0) + nvl(senat_amount, 0) + nvl(total_fcp_amount, 0)
        + nvl(total_fcp_st_amount, 0) + nvl(inss_billed_amount, 0) + nvl(ir_amount, 0) + nvl(iss_amount, 0) + nvl(csll_amount, 0),
                'FML999G999G999G999G990D00')                  total_impostos,
        d.lst_pedidos,
        h.id_boleto,
        case
            when d.source_document_type = 'PO' then
                e.bu_code
            when h.receiver_info.data[0].bu_name is null then
                org.bu_code
            else
                nvl(h.receiver_info.data[0].bu_name, h.receiver_name)
        end                                                   bu_code
    from
             rmais_efd_headers h
        inner join rmais_organizations org on org.cnpj = h.receiver_document_number
        left join tp_org              a on org.id = a.id_org
        left join tp_fornec           b on h.issuer_document_number = b.issuer_document_number
        left join rmais_status_docs   c on h.document_status = c.flag_status_docs
        left join tp_lines            d on h.efd_header_id = d.efd_header_id
        left join rmais_organizations e on h.legal_entity_cnpj = e.cnpj
        left join rmais_suppliers     f on e.cliente_id = f.id
        left join rmais_models        m on h.model = m.model
    where
        nvl(
            v('F_RMAIS'),
            0
        ) = 1
        or ( a.id_org is null
             and b.issuer_document_number is null );


-- sqlcl_snapshot {"hash":"c4ca7d9c7fa584e8e52e9bc0410c284e9a6b6b1d","type":"VIEW","name":"VW_RMAIS_EFD_HEADERS","schemaName":"RMAIS","sxml":""}